# Portals Permission Plugin Configuration
# Konfiguracja pluginu kontroli dostępu do portali

# Główne ustawienia
settings:
  # Czy plugin jest włączony
  enabled: true
  
  # Czy wyświetlać szczegółowe logi
  debug: false
  
  # Language for messages (en, pl)
  language: "en"

# Ustawienia portali
portals:
  # Czy blokować dostęp do portali Nether
  block_nether: true
  
  # Czy blokować dostęp do portali End
  block_end: true
  
  # Czy blokować niestandardowe portale (inne pluginy)
  block_custom: false

# Ustawienia knockback
knockback:
  # Czy włączyć knockback przy próbie wejścia
  enabled: true
  
  # Siła knockback (0.0 - 5.0)
  strength: 1.5
  
  # Wysokość knockback (0.0 - 3.0)
  height: 0.8
  
  # Czy odtwarzać dźwięk przy knockback
  play_sound: true
  
  # Typ dźwięku
  sound_type: "ENTITY_VILLAGER_NO"
  
  # Głośność dźwięku (0.0 - 1.0)
  sound_volume: 0.7
  
  # Wysokość dźwięku (0.5 - 2.0)
  sound_pitch: 1.0

# System cooldown
cooldown:
  # Czy włączyć cooldown na próby wejścia
  enabled: true
  
  # Czas cooldown w sekundach
  time_seconds: 5
  
  # Czy pokazywać komunikat o cooldown
  show_message: true

# Messages
messages:
  # English messages (default) - Using MiniMessage format
  en:
    no_permission_nether: "<red>You don't have permission to use Nether portals!</red>"
    no_permission_end: "<red>You don't have permission to use End portals!</red>"
    no_permission_custom: "<red>You don't have permission to use this portal!</red>"
    cooldown_active: "<yellow>You must wait <red>{time}</red> more seconds before trying again!</yellow>"
    plugin_reloaded: "<green>Portals Permission plugin has been reloaded!</green>"
    no_command_permission: "<red>You don't have permission to use this command!</red>"
    invalid_usage: "<red>Invalid usage: {usage}</red>"
  
  # Polish messages - Using MiniMessage format
  pl:
    no_permission_nether: "<red>Nie masz uprawnień do korzystania z portali Nether!</red>"
    no_permission_end: "<red>Nie masz uprawnień do korzystania z portali End!</red>"
    no_permission_custom: "<red>Nie masz uprawnień do korzystania z tego portalu!</red>"
    cooldown_active: "<yellow>Musisz poczekać jeszcze <red>{time}</red> sekund przed ponowną próbą!</yellow>"
    plugin_reloaded: "<green>Plugin Portals Permission został przeładowany!</green>"
    no_command_permission: "<red>Nie masz uprawnień do tej komendy!</red>"
    invalid_usage: "<red>Nieprawidłowe użycie: {usage}</red>"

# Uprawnienia
permissions:
  # Uprawnienie do portali Nether
  nether: "portals.nether"
  
  # Uprawnienie do portali End
  end: "portals.end"
  
  # Uprawnienie do niestandardowych portali
  custom: "portals.custom"
  
  # Uprawnienie do pominięcia wszystkich ograniczeń
  bypass: "portals.bypass"
  
  # Uprawnienie do komend administracyjnych
  admin: "portals.admin"
  
  # Uprawnienie do przeładowania pluginu
  reload: "portals.reload"